name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check format
        run: cargo fmt -- --check

  build_workspace:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Check
      run: cargo check --verbose
    - name: Check with examples
      run: cargo check --examples --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build (release)
      run: cargo build --release --verbose

  build_lib_all_features:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        run: |
          cargo build --manifest-path="splashsurf_lib/Cargo.toml" --all-targets --all-features --verbose
      - name: Run tests
        run: |
          cargo test --manifest-path="splashsurf_lib/Cargo.toml" --all-features --verbose
      - name: Run tests release mode
        run: |
          cargo test --manifest-path="splashsurf_lib/Cargo.toml" --release --all-features --verbose

  build_lib_no_default_features:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        run: |
          cargo build --manifest-path="splashsurf_lib/Cargo.toml" --all-targets --no-default-features --verbose
      - name: Run tests
        run: |
          cargo test --manifest-path="splashsurf_lib/Cargo.toml" --no-default-features --verbose
